-- ─────────────────────────────────────────────────────────────────────────────
-- StayLog · Supabase schema
--
-- Four things worth knowing before you read it:
--
--   1. Ids are text, generated by the app, not by Postgres. StayLog already
--      makes its own ids, and a device that is offline has to be able to create
--      a booking without asking a server for a key.
--
--   2. Nothing is ever hard-deleted. deleted_at is a tombstone, so a delete
--      made offline on one device can be replayed onto another. Rows with it
--      set are invisible to every read path below.
--
--   3. updated_at is the sync cursor. A trigger maintains it; the app pulls
--      "everything changed since X" and never has to diff whole tables.
--
--   4. Guest ID scans are NOT here. bookings carries the ID type and number but
--      never the photograph — those stay in the phone's own storage. Identity
--      documents in a hosted database is a bigger commitment than this feature
--      needs, so the schema makes it impossible rather than optional.
--
-- Staff read nothing directly. The base tables are yours alone; the house help
-- reaches two SECURITY DEFINER functions at the bottom that return a fixed list
-- of columns. Row-level security can only filter rows, so a policy that let her
-- read a booking row would hand her the guest's name and phone with it. A
-- function returning four named columns cannot leak a fifth.
--
-- Run once in the Supabase SQL editor.
-- ─────────────────────────────────────────────────────────────────────────────

-- ── Who owns data here ───────────────────────────────────────────────────────
create table if not exists public.owners (
  user_id  uuid primary key references auth.users on delete cascade,
  added_at timestamptz not null default now()
);

create or replace function public.is_owner()
returns boolean language sql security definer set search_path = public stable as $$
  select exists (select 1 from public.owners where user_id = auth.uid());
$$;

-- ── Shared bookkeeping ───────────────────────────────────────────────────────
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

-- ── The data ─────────────────────────────────────────────────────────────────
create table if not exists public.properties (
  id              text primary key,
  owner_id        uuid not null references auth.users on delete cascade,
  name            text not null,
  location        text,
  rooms           integer,
  price_per_night numeric,
  description     text,
  maps_link       text,
  wifi_name       text,
  wifi_password   text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  deleted_at      timestamptz
);

create table if not exists public.bookings (
  id              text primary key,
  owner_id        uuid not null references auth.users on delete cascade,
  property_id     text references public.properties on delete set null,
  guest_name      text not null,
  phone           text,
  check_in        date not null,
  check_out       date not null,
  guests          integer default 1,
  total_amount    numeric default 0,
  paid            numeric default 0,
  source          text default 'Direct',
  status          text not null default 'confirmed',
  notes           text,
  id_proof_type   text,
  id_proof_number text,
  -- id_proof_image is deliberately absent; see the header
  msg_sent        jsonb not null default '{}'::jsonb,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  deleted_at      timestamptz,
  constraint bookings_dates_ordered check (check_out > check_in)
);
create index if not exists bookings_owner_dates_idx on public.bookings (owner_id, check_in, check_out);

create table if not exists public.staff (
  id             text primary key,
  owner_id       uuid not null references auth.users on delete cascade,
  name           text not null,
  role           text,
  phone          text,
  monthly_salary numeric,
  active         boolean not null default true,
  joined_on      date,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  deleted_at     timestamptz
);

create table if not exists public.loans (
  id                 text primary key,
  owner_id           uuid not null references auth.users on delete cascade,
  staff_id           text not null references public.staff on delete cascade,
  property_id        text references public.properties on delete set null,
  principal          numeric not null,
  installment_amount numeric not null,
  disbursed_on       date not null,
  first_due_date     date,
  status             text not null default 'active',
  notes              text,
  written_off_on     date,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  deleted_at         timestamptz
);

create table if not exists public.loan_repayments (
  id         text primary key,
  owner_id   uuid not null references auth.users on delete cascade,
  loan_id    text not null references public.loans on delete cascade,
  date       date not null,
  amount     numeric not null,
  mode       text not null default 'direct',   -- 'payout' | 'direct'
  expense_id text,                              -- the payout it came off, if any
  note       text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index if not exists loan_repayments_loan_idx on public.loan_repayments (loan_id);

create table if not exists public.expenses (
  id             text primary key,
  owner_id       uuid not null references auth.users on delete cascade,
  property_id    text references public.properties on delete set null,
  staff_id       text references public.staff on delete set null,
  loan_id        text references public.loans on delete set null,
  description    text not null,
  date           date not null,
  category       text not null default 'other',
  amount         numeric not null default 0,    -- cash actually paid
  gross_amount   numeric,                       -- payout before any loan cut
  loan_deduction numeric default 0,
  paid           boolean not null default false,
  notes          text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  deleted_at     timestamptz
);
create index if not exists expenses_owner_date_idx on public.expenses (owner_id, date);

-- ── Who may look at a staff view, and whether they still may ─────────────────
create table if not exists public.staff_access (
  user_id      uuid primary key references auth.users on delete cascade,
  owner_id     uuid not null references auth.users on delete cascade,
  staff_id     text not null references public.staff on delete cascade,
  display_name text not null,
  active       boolean not null default true,
  created_at   timestamptz not null default now()
);

-- ── updated_at triggers ──────────────────────────────────────────────────────
do $$
declare t text;
begin
  foreach t in array array['properties','bookings','staff','loans','loan_repayments','expenses']
  loop
    execute format('drop trigger if exists %I_touch on public.%I', t, t);
    execute format('create trigger %I_touch before update on public.%I
                    for each row execute function public.touch_updated_at()', t, t);
  end loop;
end $$;

-- ── Row-level security: your tables are yours ────────────────────────────────
do $$
declare t text;
begin
  foreach t in array array['owners','properties','bookings','staff','loans',
                           'loan_repayments','expenses','staff_access']
  loop
    execute format('alter table public.%I enable row level security', t);
  end loop;
end $$;

do $$
declare t text;
begin
  foreach t in array array['properties','bookings','staff','loans','loan_repayments','expenses']
  loop
    execute format('drop policy if exists "owner full access" on public.%I', t);
    execute format('create policy "owner full access" on public.%I
                    for all using (owner_id = auth.uid())
                    with check (owner_id = auth.uid())', t);
  end loop;
end $$;

drop policy if exists "owner reads own row" on public.owners;
create policy "owner reads own row" on public.owners
  for select using (user_id = auth.uid());

drop policy if exists "owner manages access" on public.staff_access;
create policy "owner manages access" on public.staff_access
  for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());

-- She may read her own access row — her name, and whether she is still active.
drop policy if exists "staff reads own access" on public.staff_access;
create policy "staff reads own access" on public.staff_access
  for select using (user_id = auth.uid());

-- ── What the house help can actually call ────────────────────────────────────
-- Fixed column lists. No guest names, no phone numbers, no tariffs, no
-- payments. Deactivating her in staff_access closes both doors at once.

create or replace function public.staff_calendar(from_date date default null)
returns table (
  check_in  date,
  check_out date,
  guests    integer,
  status    text,
  property  text
)
language sql security definer set search_path = public stable as $$
  select b.check_in, b.check_out, b.guests, b.status, p.name
  from public.staff_access a
  join public.bookings b  on b.owner_id = a.owner_id
  left join public.properties p on p.id = b.property_id
  where a.user_id = auth.uid()
    and a.active
    and b.deleted_at is null
    and b.status <> 'cancelled'
    and b.check_out >= coalesce(from_date, current_date - interval '14 days')
  order by b.check_in;
$$;

create or replace function public.staff_standing()
returns jsonb
language sql security definer set search_path = public stable as $$
  select jsonb_build_object(
    'name',            a.display_name,
    'monthly_salary',  s.monthly_salary,
    'paid_this_year',  coalesce((
        select sum(e.amount) from public.expenses e
        where e.staff_id = s.id and e.paid and e.deleted_at is null
          and e.date >= date_trunc('year', current_date)
      ), 0),
    'last_payout',     (
        select jsonb_build_object('date', e.date, 'amount', e.amount)
        from public.expenses e
        where e.staff_id = s.id and e.paid and e.deleted_at is null
        order by e.date desc limit 1
      ),
    'loans',           coalesce((
        select jsonb_agg(jsonb_build_object(
                 'principal',   l.principal,
                 'instalment',  l.installment_amount,
                 'disbursed_on',l.disbursed_on,
                 'first_due',   l.first_due_date,
                 'status',      l.status,
                 'repaid',      coalesce((
                     select sum(r.amount) from public.loan_repayments r
                     where r.loan_id = l.id and r.deleted_at is null), 0)
               ) order by l.disbursed_on desc)
        from public.loans l
        where l.staff_id = s.id and l.deleted_at is null
      ), '[]'::jsonb)
  )
  from public.staff_access a
  join public.staff s on s.id = a.staff_id and s.deleted_at is null
  where a.user_id = auth.uid() and a.active;
$$;

revoke all on function public.staff_calendar(date) from public, anon;
revoke all on function public.staff_standing()    from public, anon;
grant execute on function public.staff_calendar(date) to authenticated;
grant execute on function public.staff_standing()     to authenticated;

-- ─────────────────────────────────────────────────────────────────────────────
-- After this runs, create the two accounts in Authentication → Users
-- (Add user → Create new user → tick "Auto Confirm User"), then:
--
--   insert into public.owners (user_id) values ('YOUR-UUID');
--
--   insert into public.staff_access (user_id, owner_id, staff_id, display_name)
--   values ('HER-UUID', 'YOUR-UUID', 'STAYLOG-STAFF-ID', 'Sunitha');
--
-- To end her access:
--   update public.staff_access set active = false where display_name = 'Sunitha';
--
-- To check the doors are shut, sign in as her and try:
--   select * from public.bookings;     -- expect zero rows, never an error
--   select public.staff_standing();    -- expect her own figures
-- ─────────────────────────────────────────────────────────────────────────────
